In [1]:
import torch
import numpy as np

In [4]:
simi = torch.randn(4,4)

In [5]:
simi

tensor([[-1.0621,  0.4226, -0.6607,  0.5753],
        [-0.6158,  1.7291,  0.8913, -0.2927],
        [-0.6204,  1.6215, -1.0237,  0.8424],
        [-0.2393, -2.2367, -2.0318,  0.4372]])

In [9]:
max_k_preds = np.argsort(simi.detach().cpu().numpy(), axis = 1)[:, -1:][:,::-1]

In [10]:
max_k_preds

array([[3],
       [1],
       [1],
       [3]])

In [11]:
for i, idx in enumerate(max_k_preds):
    print(idx)

[3]
[1]
[1]
[3]


In [12]:
def gen_label(labels):
    # 若为正样本对，取值为1，否则取值为0
    num = len(labels)
    gt = np.zeros(shape=(num,num))
    for i, label in enumerate(labels):
        for k in range(num):
            if labels[k] == label:
                gt[i,k] = 1
    return gt

In [13]:
label = torch.tensor([2,4,2,12], dtype = torch.long)

In [14]:
label

tensor([ 2,  4,  2, 12])

In [16]:
ground_truth = gen_label(label.detach().cpu().numpy())

In [17]:
ground_truth

array([[1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
ground_truth.shape[0]

4

In [24]:
num = 0
for i, idx in enumerate(max_k_preds):
    if ground_truth[i][idx]==1:
        num += 1
print(num/ground_truth.shape[0])

0.5
